"""Idempotent, ownership-aware project bootstrap for the PK-Stack Kiro Power."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
import tempfile
from collections.abc import Iterator
from contextlib import contextmanager
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from pstack_kiro.branding import DISPLAY_NAME, DISTRIBUTION_NAME, RECEIPT_MANAGER
from pstack_kiro.discovery import discover_repository
from pstack_kiro.paths import WorkspacePathError, ensure_tree_no_symlinks, workspace_path

try:
    import fcntl
except ImportError:  # pragma: no cover - project targets macOS/Linux
    fcntl = None  # type: ignore[assignment]

BOOTSTRAP_SCHEMA = 1
RECEIPT = Path(".pstack/bootstrap.json")
DISCOVERY = Path(".pstack/discovery.json")
SKILL_PARITY_ASSET = Path("docs/upstream-skill-parity.json")
MAX_SKILL_PARITY_BYTES = 512 * 1024
ALLOWED_SKILL_DISPOSITIONS = {
    "direct-port",
    "alias-consolidation",
    "native-kiro-replacement",
    "excluded",
}
REQUIRED_SOURCE_MODULES = (
    "__init__.py",
    "__main__.py",
    "bootstrap.py",
    "branding.py",
    "cli.py",
    "discovery.py",
    "doctor.py",
    "features.py",
    "goal.py",
    "knowledge.py",
    "models.py",
    "paths.py",
    "runner.py",
    "upstreams.py",
)
REQUIRED_POWER_ASSETS = (
    SKILL_PARITY_ASSET.as_posix(),
    "skills/setup-pstack/scripts/setup_pstack.py",
    "skills/principles/references/catalog.md",
    "dev.kiro/steering/pstack-core.md",
    "dev.kiro/steering/pstack-safety.md",
    "dev.kiro/steering/pstack-typescript.md",
    "dev.kiro/steering/pstack-unslop.md",
    "templates/project/.kiro/agents/pstack.json",
    "templates/project/.kiro/agents/pstack-architect.json",
    "templates/project/.kiro/agents/pstack-reviewer.json",
    "templates/project/.kiro/agents/pstack-verifier.json",
    "templates/project/.kiro/hooks/pstack-session.json",
    "templates/project/.kiro/hooks/pstack-tripwire.json",
    "templates/projectctl/uv.lock",
)
GITIGNORE_BLOCK = f"""# {DISPLAY_NAME} runtime state (generated by /setup-pstack)
.pstack/state/
.pstack/tmp/
.pstack/projectctl/.venv/
.pk-stack-maintenance/
"""
LEGACY_GITIGNORE_BLOCK = f"""# {DISPLAY_NAME} runtime state (generated by /setup-pstack)
.pstack/state/
.pstack/tmp/
.pstack/projectctl/.venv/
"""
# Existing setup consumers may treat inventory values as machine keys.
GITIGNORE_RESULT_KEY = ".gitignore:pstack-runtime-block"

TARGET_PYPROJECT = f"""[project]
name = "{DISTRIBUTION_NAME}"
version = "0.1.0"
description = "Repo-local {DISPLAY_NAME} project control surface"
requires-python = ">=3.11"
dependencies = [
  "cyclopts==4.23.2",
  "PyYAML>=6.0.2,<7",
]

[tool.uv]
package = false
"""

INTERNAL_WRAPPER = """#!/bin/sh
set -eu
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)
PROJECTCTL_ROOT="$SCRIPT_DIR/../projectctl"
cd "$PROJECT_ROOT"
if [ "${PYTHONPATH+x}" = x ]; then
  PSTACK_KIRO_CALLER_PYTHONPATH_SET=1
  PSTACK_KIRO_CALLER_PYTHONPATH=$PYTHONPATH
else
  PSTACK_KIRO_CALLER_PYTHONPATH_SET=0
  PSTACK_KIRO_CALLER_PYTHONPATH=
fi
export PSTACK_KIRO_CALLER_PYTHONPATH_SET PSTACK_KIRO_CALLER_PYTHONPATH
uv sync --quiet --locked --no-config --project "$PROJECTCTL_ROOT"
PYTHONPATH="$PROJECTCTL_ROOT/src" \
  exec "$PROJECTCTL_ROOT/.venv/bin/python" -B -X pycache_prefix=/dev/null \
    -m pstack_kiro "$@"
"""

ROOT_WRAPPER = """#!/bin/sh
set -eu
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
exec "$SCRIPT_DIR/.pstack/bin/projectctl" "$@"
"""

TARGET_README = f"""# Repo-local projectctl

This directory is managed by the {DISPLAY_NAME} bootstrap. Use the canonical
`.pstack/bin/projectctl` entrypoint. A bootstrap-managed `./projectctl` may also
exist as a convenience, but workflows never select an ambient root executable.

The cached controller is not setup authority. Setup and refresh must use the
Power-local `/setup-pstack` skill, or an explicitly reviewed `--power-root`;
`projectctl setup` fails closed when that source is omitted.

Runtime goal state lives in `.pstack/state/` and is intentionally ignored.
"""

FEATURE_README = """# Feature map

This directory is the narrow **PROVE** interface. Each feature file describes
one user-observable behavior and binds it to one explicitly reviewed executable
verification command. Broader architecture, decisions, concepts, and
operations belong elsewhere in `Wiki/` (the **KNOW** interface).

Create a contract with:

```bash
.pstack/bin/projectctl feature generate account-lookup \\
  --title "Account lookup" \\
  --behavior "A caller can retrieve account status." \\
  --expected-path "Runtime -> gateway -> account service -> response" \\
  --sub-feature "lookup-status=Return the current account status." \\
  --entrypoint "cli=Run the account lookup command." \\
  --drive "cli=Run the public command from the project root." \\
  --entrypoint-proof "cli=The command exits zero and prints the expected status." \\
  --gotcha "A zero exit without the expected status is insufficient." \\
  --evidence-boundary "Retain bounded public output and its exit status." \\
  --cleanup-boundary "Remove only verifier-owned temporary state." \\
  --command "uv run pytest tests/test_account_lookup.py" \\
  --ready
```

Schema-2 contracts map sub-features, every user entrypoint, a same-name drive
recipe and observable proof for each entrypoint, gotchas, and evidence/cleanup
boundaries. Generated contracts default to `draft: true`. With `--ready`,
projectctl runs the command first and writes a ready contract only when that
proof passes.

For an initial map, prepare one exact JSON object containing 3-5 complete
schema-2 feature records, then prove only one representative:

```bash
.pstack/bin/projectctl feature generate-map feature-plan.json \\
  --representative account-lookup
```

The remaining records stay drafts until each is independently proven with
`.pstack/bin/projectctl feature publish <slug>`.
"""


@dataclass(slots=True)
class BootstrapResult:
    root: str
    dry_run: bool
    update_managed: bool
    created: list[str] = field(default_factory=list)
    updated: list[str] = field(default_factory=list)
    pending_updates: list[str] = field(default_factory=list)
    stale_managed: list[str] = field(default_factory=list)
    unchanged: list[str] = field(default_factory=list)
    conflicts: list[str] = field(default_factory=list)
    notes: list[str] = field(default_factory=list)
    discovery: dict[str, Any] = field(default_factory=dict)

    @property
    def ok(self) -> bool:
        return not self.conflicts and not self.pending_updates and not self.stale_managed

    def to_dict(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "root": self.root,
            "dry_run": self.dry_run,
            "update_managed": self.update_managed,
            "created": self.created,
            "updated": self.updated,
            "pending_updates": self.pending_updates,
            "stale_managed": self.stale_managed,
            "unchanged": self.unchanged,
            "conflicts": self.conflicts,
            "notes": self.notes,
            "discovery": self.discovery,
        }


@dataclass(frozen=True, slots=True)
class BootstrapReceiptAudit:
    """Read-only comparison of a bootstrap receipt with its managed files."""

    managed_count: int
    missing: tuple[str, ...]
    hash_mismatches: tuple[str, ...]
    unsafe_or_unreadable: tuple[str, ...]

    @property
    def ok(self) -> bool:
        return not (self.missing or self.hash_mismatches or self.unsafe_or_unreadable)


def bootstrap_project(
    root: Path,
    *,
    power_root: Path | None = None,
    dry_run: bool = False,
    update_managed: bool = False,
) -> BootstrapResult:
    root = root.resolve()
    if not root.is_dir():
        raise ValueError(f"project root does not exist: {root}")
    with _bootstrap_lock(root):
        return _bootstrap_project_locked(
            root,
            power_root=power_root,
            dry_run=dry_run,
            update_managed=update_managed,
        )


def _bootstrap_project_locked(
    root: Path,
    *,
    power_root: Path | None,
    dry_run: bool,
    update_managed: bool,
) -> BootstrapResult:
    cache_root = workspace_path(root, Path(".pstack"))
    if power_root is not None:
        requested_asset_root = Path(os.path.abspath(power_root))
        if _same_or_descendant(requested_asset_root, cache_root):
            _raise_cached_authority()
        asset_root = _resolve_power_source(power_root)
        source_package = asset_root / "src" / "pstack_kiro"
    else:
        checkout_root = Path(__file__).resolve().parents[2]
        checkout_package = checkout_root / "src" / "pstack_kiro"
        if checkout_package.is_dir():
            asset_root = checkout_root
            source_package = checkout_package
        else:
            source_package = Path(__file__).resolve().parent
            asset_root = source_package / "_assets"
    if _same_or_descendant(asset_root, cache_root):
        _raise_cached_authority()
    template_root = asset_root / "templates" / "project"
    if not source_package.is_dir():
        raise ValueError(f"{DISPLAY_NAME} source package is missing: {source_package}")
    _validate_power_assets(asset_root, source_package)
    projectctl_lock = asset_root / "templates" / "projectctl" / "uv.lock"

    receipt_path = workspace_path(root, RECEIPT)
    if receipt_path.exists() and not receipt_path.is_file():
        raise ValueError(f"{DISPLAY_NAME} ownership receipt path is not a file: {receipt_path}")
    old_receipt = _load_receipt(root)
    previous_hashes = old_receipt.get("files", {}) if old_receipt else {}
    operations: list[tuple[Path, bytes, bool]] = []
    notes: list[str] = []

    for source in sorted(source_package.glob("*.py")):
        relative = Path(".pstack/projectctl/src/pstack_kiro") / source.name
        operations.append((relative, source.read_bytes(), False))

    asset_sources = (
        (asset_root / "skills", Path(".kiro/skills"), Path(".pstack/projectctl/skills")),
        (
            asset_root / "dev.kiro" / "steering",
            Path(".kiro/steering"),
            Path(".pstack/projectctl/dev.kiro/steering"),
        ),
    )
    for directory, destination_base, cache_base in asset_sources:
        if not directory.is_dir():
            notes.append(f"Optional Kiro asset source is absent: {directory}")
            continue
        for source in sorted(path for path in directory.rglob("*") if path.is_file()):
            suffix = source.relative_to(directory)
            executable = os.access(source, os.X_OK)
            content = source.read_bytes()
            # The setup skill must keep its Power-local origin so an upgraded
            # Power cannot be shadowed by a stale workspace copy.
            if not (
                destination_base == Path(".kiro/skills")
                and suffix.parts
                and suffix.parts[0] == "setup-pstack"
            ):
                operations.append((destination_base / suffix, content, executable))
            operations.append((cache_base / suffix, content, executable))

    generated = {
        Path(".pstack/projectctl/pyproject.toml"): TARGET_PYPROJECT.encode(),
        Path(".pstack/projectctl/uv.lock"): projectctl_lock.read_bytes(),
        Path(".pstack/projectctl/templates/projectctl/uv.lock"): projectctl_lock.read_bytes(),
        Path(".pstack/projectctl/README.md"): TARGET_README.encode(),
        Path(".pstack/bin/projectctl"): INTERNAL_WRAPPER.encode(),
        Path("Wiki/features/README.md"): FEATURE_README.encode(),
    }
    for relative, content in generated.items():
        operations.append((relative, content, relative == Path(".pstack/bin/projectctl")))

    if template_root.is_dir():
        for source in sorted(path for path in template_root.rglob("*") if path.is_file()):
            relative = source.relative_to(template_root)
            cached = Path(".pstack/projectctl/templates/project") / relative
            executable = os.access(source, os.X_OK)
            operations.extend(
                (
                    (relative, source.read_bytes(), executable),
                    (cached, source.read_bytes(), executable),
                )
            )
    else:
        notes.append(f"No project templates were found at {template_root}.")

    root_wrapper = root / "projectctl"
    if not root_wrapper.exists() or "projectctl" in previous_hashes:
        operations.append((Path("projectctl"), ROOT_WRAPPER.encode(), True))
    else:
        notes.append(
            "An existing root projectctl was preserved; use .pstack/bin/projectctl or integrate "
            f"the {DISPLAY_NAME} commands into the existing project CLI."
        )

    initial_discovery = discover_repository(root)
    initial_discovery_content = (
        json.dumps(initial_discovery, indent=2, sort_keys=True) + "\n"
    ).encode()
    preview_operations = [*operations, (DISCOVERY, initial_discovery_content, False)]
    preview = BootstrapResult(
        root=str(root),
        dry_run=True,
        update_managed=update_managed,
        notes=list(notes),
        discovery=initial_discovery,
    )
    preview_hashes: dict[str, str] = {}
    for relative, content, executable in preview_operations:
        _apply_file(
            root,
            relative,
            content,
            previous_hashes=previous_hashes,
            managed_hashes=preview_hashes,
            result=preview,
            update_managed=update_managed,
            executable=executable,
            refresh_owned=relative == DISCOVERY,
        )
    current_keys = {relative.as_posix() for relative, _, _ in preview_operations}
    for key in sorted(set(previous_hashes) - current_keys):
        stale_path = workspace_path(root, Path(key))
        if stale_path.exists():
            preview.stale_managed.append(key)
    _ensure_gitignore(root, result=preview, dry_run=True)
    if not preview.ok:
        preview.dry_run = dry_run
        preview.notes.append("No managed files were written because preflight found blockers.")
        return preview
    if dry_run:
        return preview

    result = BootstrapResult(
        root=str(root),
        dry_run=False,
        update_managed=update_managed,
        notes=notes,
    )
    managed_hashes: dict[str, str] = {}
    for relative, content, executable in operations:
        _apply_file(
            root,
            relative,
            content,
            previous_hashes=previous_hashes,
            managed_hashes=managed_hashes,
            result=result,
            update_managed=update_managed,
            executable=executable,
        )
    _ensure_gitignore(root, result=result, dry_run=False)
    result.discovery = discover_repository(root)
    discovery_content = (json.dumps(result.discovery, indent=2, sort_keys=True) + "\n").encode()
    _apply_file(
        root,
        DISCOVERY,
        discovery_content,
        previous_hashes=previous_hashes,
        managed_hashes=managed_hashes,
        result=result,
        update_managed=update_managed,
        refresh_owned=True,
    )
    if not result.ok:
        result.notes.append(
            "Workspace contents changed after preflight; no ownership receipt was committed."
        )
        return result

    receipt_payload = {
        "schema_version": BOOTSTRAP_SCHEMA,
        "manager": RECEIPT_MANAGER,
        "files": dict(sorted(managed_hashes.items())),
    }
    _verify_managed_hashes(root, managed_hashes)
    receipt_content = (json.dumps(receipt_payload, indent=2, sort_keys=True) + "\n").encode()
    _write_if_changed(workspace_path(root, RECEIPT), receipt_content, executable=False)
    return result


@contextmanager
def _bootstrap_lock(root: Path) -> Iterator[None]:
    """Serialize setup without creating a project file during preflight."""

    if fcntl is None:
        raise OSError(f"{DISPLAY_NAME} setup requires fcntl locking on this platform")
    flags = os.O_RDONLY | getattr(os, "O_DIRECTORY", 0) | getattr(os, "O_CLOEXEC", 0)
    descriptor = os.open(root, flags)
    try:
        fcntl.flock(descriptor, fcntl.LOCK_EX)
        yield
    finally:
        fcntl.flock(descriptor, fcntl.LOCK_UN)
        os.close(descriptor)


def _verify_managed_hashes(root: Path, managed_hashes: dict[str, str]) -> None:
    audit = _audit_managed_hashes(root, managed_hashes)
    failures = sorted((*audit.missing, *audit.hash_mismatches, *audit.unsafe_or_unreadable))
    if failures:
        raise OSError(
            "managed files changed during setup before receipt commit: " + ", ".join(failures)
        )


def audit_bootstrap_receipt(root: Path) -> BootstrapReceiptAudit:
    """Validate and audit every managed path in the bootstrap receipt without writing."""

    receipt_path = workspace_path(root, RECEIPT)
    if not receipt_path.exists():
        raise ValueError(f"{DISPLAY_NAME} ownership receipt is missing at {receipt_path}")
    if not receipt_path.is_file():
        raise ValueError(f"{DISPLAY_NAME} ownership receipt is not a file at {receipt_path}")
    receipt = _load_receipt(root)
    if receipt is None:  # Defensive: existence and type were checked above.
        raise ValueError(f"{DISPLAY_NAME} ownership receipt is missing at {receipt_path}")
    managed_hashes: dict[str, str] = receipt["files"]
    return _audit_managed_hashes(root, managed_hashes)


def _audit_managed_hashes(root: Path, managed_hashes: dict[str, str]) -> BootstrapReceiptAudit:
    missing: list[str] = []
    hash_mismatches: list[str] = []
    unsafe_or_unreadable: list[str] = []
    for key, expected in sorted(managed_hashes.items()):
        try:
            path = workspace_path(root, Path(key))
            if not path.is_file():
                missing.append(key)
            elif _hash(path.read_bytes()) != expected:
                hash_mismatches.append(key)
        except (OSError, ValueError):
            unsafe_or_unreadable.append(key)
    return BootstrapReceiptAudit(
        managed_count=len(managed_hashes),
        missing=tuple(missing),
        hash_mismatches=tuple(hash_mismatches),
        unsafe_or_unreadable=tuple(unsafe_or_unreadable),
    )


def _load_receipt(root: Path) -> dict[str, Any] | None:
    path = workspace_path(root, RECEIPT)
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"invalid {DISPLAY_NAME} ownership receipt at {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise ValueError(f"{DISPLAY_NAME} ownership receipt must be a JSON object at {path}")
    if (
        type(data.get("schema_version")) is not int
        or data["schema_version"] != BOOTSTRAP_SCHEMA
        or type(data.get("manager")) is not str
        or data["manager"] != RECEIPT_MANAGER
    ):
        raise ValueError(f"unrecognized {DISPLAY_NAME} ownership receipt at {path}")
    files = data.get("files")
    if (
        not isinstance(files, dict)
        or not files
        or not all(
            _valid_receipt_key(key)
            and isinstance(value, str)
            and re.fullmatch(r"[0-9a-f]{64}", value)
            for key, value in files.items()
        )
    ):
        raise ValueError(
            f"invalid managed-file hashes in {DISPLAY_NAME} ownership receipt at {path}"
        )
    return data


def _valid_receipt_key(value: Any) -> bool:
    if type(value) is not str or not value:
        return False
    path = Path(value)
    return (
        not path.is_absolute()
        and path.as_posix() == value
        and all(part not in {"", ".", ".."} for part in path.parts)
    )


def _validate_power_assets(asset_root: Path, source_package: Path) -> None:
    try:
        source_relative = source_package.relative_to(asset_root)
    except ValueError:
        ensure_tree_no_symlinks(source_package.parent, Path(source_package.name))
    else:
        ensure_tree_no_symlinks(asset_root, source_relative)
    for relative in ("skills", "dev.kiro/steering", "templates/project", "templates/projectctl"):
        ensure_tree_no_symlinks(asset_root, Path(relative))
    missing = [
        f"src/pstack_kiro/{name}"
        for name in REQUIRED_SOURCE_MODULES
        if not (source_package / name).is_file()
    ]
    missing.extend(
        relative for relative in REQUIRED_POWER_ASSETS if not (asset_root / relative).is_file()
    )
    if missing:
        joined = ", ".join(sorted(missing))
        raise ValueError(f"required {DISPLAY_NAME} Power assets are missing: {joined}")
    _validate_skill_catalog(asset_root)


def _validate_skill_catalog(asset_root: Path) -> tuple[str, ...]:
    """Require the bounded parity catalog to name every shipped skill exactly once."""

    path = asset_root / SKILL_PARITY_ASSET
    try:
        raw = path.read_bytes()
    except OSError as exc:
        raise ValueError(f"unable to read {DISPLAY_NAME} skill parity catalog: {path}") from exc
    if len(raw) > MAX_SKILL_PARITY_BYTES:
        raise ValueError(
            f"{DISPLAY_NAME} skill parity catalog exceeds {MAX_SKILL_PARITY_BYTES} bytes"
        )
    try:
        document = json.loads(raw)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError(f"invalid {DISPLAY_NAME} skill parity catalog: {exc}") from exc
    if not isinstance(document, dict) or document.get("schema_version") != 1:
        raise ValueError(f"invalid {DISPLAY_NAME} skill parity catalog schema")
    raw_skills = document.get("skills")
    raw_pk_only = document.get("pk_only_skills")
    if not isinstance(raw_skills, list) or not raw_skills:
        raise ValueError(f"invalid {DISPLAY_NAME} upstream skill inventory")
    if not isinstance(raw_pk_only, list):
        raise ValueError(f"invalid {DISPLAY_NAME} PK-only skill inventory")

    upstream_names: list[str] = []
    routed_names: list[str] = []
    for index, entry in enumerate(raw_skills):
        if not isinstance(entry, dict):
            raise ValueError(f"skill parity entry {index} must be an object")
        name = entry.get("name")
        disposition = entry.get("disposition")
        target = entry.get("target")
        if type(name) is not str or not re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name):
            raise ValueError(f"skill parity entry {index} has an invalid name")
        upstream_names.append(name)
        if disposition not in ALLOWED_SKILL_DISPOSITIONS:
            raise ValueError(f"skill parity entry {name!r} has an invalid disposition")
        if disposition == "excluded":
            if target is not None:
                raise ValueError(f"excluded skill {name!r} must not have a runnable target")
            continue
        if target != f"skills/{name}/SKILL.md":
            raise ValueError(f"routed skill {name!r} must target its canonical skill file")
        routed_names.append(name)
    pk_only = [
        name
        for name in raw_pk_only
        if type(name) is str and re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", name)
    ]
    if len(pk_only) != len(raw_pk_only):
        raise ValueError(f"invalid {DISPLAY_NAME} PK-only skill name")
    if upstream_names != sorted(set(upstream_names)):
        raise ValueError(f"{DISPLAY_NAME} upstream skill inventory must be sorted and unique")
    if pk_only != sorted(set(pk_only)) or set(pk_only) & set(upstream_names):
        raise ValueError(f"{DISPLAY_NAME} PK-only skill inventory must be sorted and disjoint")

    expected = set(routed_names) | set(pk_only)
    skill_root = asset_root / "skills"
    actual = {
        child.name
        for child in skill_root.iterdir()
        if child.is_dir() and (child / "SKILL.md").is_file()
    }
    unexpected_directories = sorted(
        child.name
        for child in skill_root.iterdir()
        if child.is_dir() and not (child / "SKILL.md").is_file()
    )
    if actual != expected or unexpected_directories:
        missing = sorted(expected - actual)
        extra = sorted(actual - expected)
        details: list[str] = []
        if missing:
            details.append("missing " + ", ".join(missing))
        if extra:
            details.append("unexpected " + ", ".join(extra))
        if unexpected_directories:
            details.append("directories without SKILL.md " + ", ".join(unexpected_directories))
        raise ValueError(f"{DISPLAY_NAME} skill catalog mismatch: {'; '.join(details)}")
    summary = document.get("summary")
    if not isinstance(summary, dict) or summary.get("shipped_skill_directories") != len(expected):
        raise ValueError(f"{DISPLAY_NAME} skill parity summary does not match the catalog")
    return tuple(sorted(expected))


def _resolve_power_source(path: Path) -> Path:
    try:
        return path.resolve()
    except (OSError, RuntimeError, ValueError) as exc:
        raise WorkspacePathError(f"unable to resolve the {DISPLAY_NAME} Power source path") from exc


def _same_or_descendant(candidate: Path, boundary: Path) -> bool:
    """Use lexical ancestry plus filesystem identity for case-folding volumes."""

    candidate_absolute = Path(os.path.abspath(candidate))
    boundary_absolute = Path(os.path.abspath(boundary))
    try:
        candidate_absolute.relative_to(boundary_absolute)
    except ValueError:
        pass
    else:
        return True

    if not boundary_absolute.exists():
        return False
    for ancestor in (candidate_absolute, *candidate_absolute.parents):
        if not ancestor.exists():
            continue
        try:
            if ancestor.samefile(boundary_absolute):
                return True
        except OSError as exc:
            raise WorkspacePathError(
                f"unable to compare the {DISPLAY_NAME} Power source path"
            ) from exc
    return False


def _raise_cached_authority() -> None:
    raise ValueError(
        "refusing to use the project-local .pstack cache as setup authority; "
        "run the Power-local /setup-pstack skill or pass an external reviewed --power-root"
    )


def _apply_file(
    root: Path,
    relative: Path,
    content: bytes,
    *,
    previous_hashes: dict[str, str],
    managed_hashes: dict[str, str],
    result: BootstrapResult,
    update_managed: bool,
    executable: bool = False,
    refresh_owned: bool = False,
) -> None:
    key = relative.as_posix()
    destination = workspace_path(root, relative)
    parent_blocker = _existing_parent_blocker(root, relative)
    if parent_blocker is not None:
        if parent_blocker not in result.conflicts:
            result.conflicts.append(parent_blocker)
        return
    if destination.exists() and not destination.is_file():
        result.conflicts.append(key)
        return
    desired_hash = _hash(content)
    previous_hash = previous_hashes.get(key)
    existing_hash = _hash(destination.read_bytes()) if destination.is_file() else None

    if existing_hash == desired_hash:
        managed_hashes[key] = desired_hash
        result.unchanged.append(key)
        if not result.dry_run:
            destination.chmod(0o755 if executable else 0o644)
        return
    if existing_hash is not None:
        if existing_hash != previous_hash:
            if previous_hash is not None:
                managed_hashes[key] = previous_hash
            result.conflicts.append(key)
            return
        if not update_managed and not refresh_owned:
            managed_hashes[key] = existing_hash
            result.pending_updates.append(key)
            return

    action = result.created if existing_hash is None else result.updated
    action.append(key)
    managed_hashes[key] = desired_hash
    if not result.dry_run:
        _atomic_write(destination, content, executable=executable)


def _ensure_gitignore(root: Path, *, result: BootstrapResult, dry_run: bool) -> None:
    path = workspace_path(root, Path(".gitignore"))
    if path.exists() and not path.is_file():
        result.conflicts.append(GITIGNORE_RESULT_KEY)
        return
    existing = path.read_text(encoding="utf-8") if path.is_file() else ""
    ignored_paths = (
        ".pstack/state/",
        ".pstack/tmp/",
        ".pstack/projectctl/.venv/",
        ".pk-stack-maintenance/",
    )
    migrated = _migrate_gitignore_managed_blocks(existing)
    if migrated is not None:
        content = migrated
    elif all(gitignore_has_entry(existing, ignored_path) for ignored_path in ignored_paths):
        result.unchanged.append(GITIGNORE_RESULT_KEY)
        return
    else:
        prefix = "" if not existing or existing.endswith("\n") else "\n"
        separator = "" if not existing else "\n"
        content = f"{existing}{prefix}{separator}{GITIGNORE_BLOCK}"
    if content == existing:
        result.unchanged.append(GITIGNORE_RESULT_KEY)
        return
    if path.exists():
        result.updated.append(GITIGNORE_RESULT_KEY)
    else:
        result.created.append(GITIGNORE_RESULT_KEY)
    if not dry_run:
        _atomic_write(path, content.encode(), executable=False)


def _migrate_gitignore_managed_blocks(text: str) -> str | None:
    """Replace legacy/current generated blocks with one canonical in-place block."""

    lines = text.splitlines()
    current = GITIGNORE_BLOCK.splitlines()
    legacy = LEGACY_GITIGNORE_BLOCK.splitlines()

    def block_length(index: int) -> int:
        if lines[index : index + len(current)] == current:
            return len(current)
        if lines[index : index + len(legacy)] == legacy:
            return len(legacy)
        return 0

    output: list[str] = []
    found = False
    inserted = False
    index = 0
    while index < len(lines):
        length = block_length(index)
        if not length:
            output.append(lines[index])
            index += 1
            continue
        found = True
        if not inserted:
            output.extend(current)
            inserted = True
        index += length
        following = index
        while following < len(lines) and not lines[following]:
            following += 1
        if following < len(lines) and block_length(following):
            index = following

    if not found:
        return None
    normalized = "\n".join(output)
    return normalized + ("\n" if text.endswith("\n") else "")


def gitignore_has_entry(text: str, entry: str) -> bool:
    """Return whether ``entry`` is a real, uncommented gitignore pattern."""

    return any(
        line.strip() == entry
        for line in text.splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    )


def _existing_parent_blocker(root: Path, relative: Path) -> str | None:
    """Return the first existing non-directory parent of a managed file."""

    current = root
    for part in relative.parent.parts:
        current /= part
        if current.exists() and not current.is_dir():
            return current.relative_to(root).as_posix()
    return None


def _atomic_write(path: Path, content: bytes, *, executable: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        mode = 0o755 if executable else 0o644
        os.chmod(temporary, mode)
        os.replace(temporary, path)
    except BaseException:
        Path(temporary).unlink(missing_ok=True)
        raise


def _write_if_changed(path: Path, content: bytes, *, executable: bool) -> None:
    if path.is_file() and path.read_bytes() == content:
        path.chmod(0o755 if executable else 0o644)
        return
    _atomic_write(path, content, executable=executable)


def _hash(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--power-root", type=Path)
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--update-managed",
        action="store_true",
        help="replace only files matching the prior receipt after reviewing a dry run",
    )
    parser.add_argument("--output", choices=("json", "text"), default="text")
    args = parser.parse_args(argv)
    try:
        result = bootstrap_project(
            args.root,
            power_root=args.power_root,
            dry_run=args.dry_run,
            update_managed=args.update_managed,
        )
    except (OSError, ValueError) as exc:
        payload = {"ok": False, "error": str(exc), "error_type": type(exc).__name__}
        if args.output == "json":
            print(json.dumps(payload, indent=2, sort_keys=True))
        else:
            print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(2) from None
    if args.output == "json":
        print(json.dumps(result.to_dict(), indent=2, sort_keys=True))
    else:
        print(f"{DISPLAY_NAME} setup {'would update' if args.dry_run else 'updated'} {result.root}")
        for label in (
            "created",
            "updated",
            "pending_updates",
            "stale_managed",
            "unchanged",
            "conflicts",
        ):
            values = getattr(result, label)
            print(f"{label}: {len(values)}")
            for value in values:
                print(f"  - {value}")
        for note in result.notes:
            print(f"note: {note}")
    if not result.ok:
        sys.exit(2)


if __name__ == "__main__":
    main()
